import { ArrowUpRight, Check, Eye, Mail, MessageCircle, Network, Phone, Router, Satellite, ShieldCheck, Wifi, Zap } from "lucide-react";
import { motion } from "framer-motion";
import SiteLayout from "@/components/SiteLayout";

const services = [{ icon: Satellite, name: "Starlink installation", detail: "Assessment, mount, cable path, router placement and a tested setup.", image: "/WhatsApp Image 2026-09-08 at 07.05.34.jpeg" }, { icon: Eye, name: "CCTV & security", detail: "Cameras, recording and secure remote viewing configured around your site.", image: "/WhatsApp Image 2026-09-08 at 07.04.31.jpeg" }, { icon: Wifi, name: "Wi-Fi coverage", detail: "Access points and cabling that remove dead zones without cluttering the property.", image: "/WhatsApp Image 2026-09-08 at 07.05.35 (1).jpeg" }];
const extras = [{ icon: Zap, name: "Fibre internet" }, { icon: Network, name: "GPON / FTTH" }, { icon: Router, name: "Network design" }, { icon: ShieldCheck, name: "Smart systems" }];
function Hero({ eyebrow, title, text }: { eyebrow: string; title: string; text: string }) { return <section className="atlas-page-hero"><div className="atlas-wrap"><motion.p initial={{ opacity: 0, y: 14 }} animate={{ opacity: 1, y: 0 }} className="atlas-eyebrow"><span />{eyebrow}</motion.p><motion.h1 initial={{ opacity: 0, y: 24 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: .07 }}>{title}</motion.h1><motion.p initial={{ opacity: 0, y: 18 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: .13 }} className="atlas-lede">{text}</motion.p></div></section>; }
export function ServicesPage() { return <SiteLayout><Hero eyebrow="Services" title="The systems your property depends on." text="Choose one service or plan the whole site together. We make the technical decisions clear before the work begins." /><section className="atlas-page-section"><div className="atlas-wrap atlas-service-list-large">{services.map((service, index) => <motion.article key={service.name} initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }}><div><span>0{index + 1}</span><service.icon size={23} /><h2>{service.name}</h2><p>{service.detail}</p><a href="/contact" className="atlas-link">Talk through your site <ArrowUpRight size={16} /></a></div><img src={service.image} alt={service.name} loading="lazy" /></motion.article>)}</div><div className="atlas-wrap atlas-extras">{extras.map((extra) => <a href="/contact" key={extra.name}><extra.icon size={19} />{extra.name}<ArrowUpRight size={15} /></a>)}</div></section></SiteLayout>; }
export function WorkPage() { return <SiteLayout><Hero eyebrow="Our work" title="Work that has to keep working." text="The finish matters. So do the parts most people never see: the route behind a wall, the hardware choice and the test before handover." /><section className="atlas-page-section"><div className="atlas-wrap atlas-case-grid"><figure className="atlas-case-large"><img src="/WhatsApp Image 2026-09-08 at 07.04.30 (1).jpeg" alt="SparkLink installation team working on site" loading="lazy" /><figcaption>01 / Field installation</figcaption></figure><div className="atlas-case-copy"><p className="atlas-eyebrow"><span />What good looks like</p><h2>The technical detail is the visible difference.</h2>{["Equipment selected for the space and workload", "Cable runs that stay neat and protected", "Settings verified before you rely on them"].map((item) => <p key={item}><Check size={16} />{item}</p>)}</div><figure className="atlas-case-small"><img src="/WhatsApp Image 2026-09-08 at 07.04.31.jpeg" alt="CCTV camera installed by SparkLink" loading="lazy" /><figcaption>02 / Security systems</figcaption></figure></div></section></SiteLayout>; }
export function AboutPage() { return <SiteLayout><Hero eyebrow="About SparkLink" title="A practical team for the parts of technology that cannot fail." text="We install connectivity, security and infrastructure for clients who want a clear plan and one accountable team." /><section className="atlas-page-section atlas-about-page"><div className="atlas-wrap atlas-about-page-grid"><img src="/WhatsApp Image 2026-09-08 at 07.05.34.jpeg" alt="Starlink dish installed on a rooftop" loading="lazy" /><div><p className="atlas-eyebrow"><span />Our approach</p><h2>Know the site.<br />Do it properly.</h2><p>Every property has its own constraints. We start by understanding yours, then build an installation that works cleanly now and makes sense when it is time to grow.</p><a className="atlas-button atlas-button-dark" href="/contact">Talk to SparkLink <ArrowUpRight size={17} /></a></div></div></section></SiteLayout>; }
export function ContactPage() { return <SiteLayout><Hero eyebrow="Contact" title="Start with the site you have." text="Send us a short message with what you want to improve. We will help you work out the next useful step." /><section className="atlas-page-section"><div className="atlas-wrap atlas-contact-grid"><a href="https://wa.me/263773791578" target="_blank" rel="noreferrer"><MessageCircle size={23} /><span>WhatsApp</span><strong>Start a conversation <ArrowUpRight size={16} /></strong></a><a href="tel:+263773791578"><Phone size={23} /><span>Call</span><strong>+263 77 379 1578</strong></a><a href="mailto:nicodimusmlambo@gmail.com"><Mail size={23} /><span>Email</span><strong>nicodimusmlambo@gmail.com</strong></a></div></section></SiteLayout>; }
